create table if not exists public.app_state_directory_history (
  history_id bigint generated by default as identity primary key,
  workspace_id text not null,
  people jsonb not null default '[]'::jsonb,
  drug_testing_roster jsonb not null default '[]'::jsonb,
  source_updated_at timestamptz,
  saved_at timestamptz not null default now()
);

create index if not exists app_state_directory_history_workspace_saved_idx
  on public.app_state_directory_history (workspace_id, saved_at desc);

alter table public.app_state_directory_history enable row level security;

create or replace function public.preserve_app_state_directory()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if old.data->'people' is distinct from new.data->'people'
     or old.data->'drugTestingRoster' is distinct from new.data->'drugTestingRoster' then
    insert into public.app_state_directory_history (
      workspace_id,
      people,
      drug_testing_roster,
      source_updated_at
    )
    values (
      old.id,
      coalesce(old.data->'people', '[]'::jsonb),
      coalesce(old.data->'drugTestingRoster', '[]'::jsonb),
      old.updated_at
    );

    delete from public.app_state_directory_history
    where history_id in (
      select history_id
      from public.app_state_directory_history
      where workspace_id = old.id
      order by saved_at desc, history_id desc
      offset 100
    );
  end if;

  return new;
end;
$$;

drop trigger if exists preserve_app_state_directory_before_update on public.app_state;

create trigger preserve_app_state_directory_before_update
before update on public.app_state
for each row
execute function public.preserve_app_state_directory();

revoke all on public.app_state_directory_history from anon, authenticated;
revoke all on function public.preserve_app_state_directory() from public, anon, authenticated;
